// <auto-generated />
using System;
using CAC_Management.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CAC_Management.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191129071055_addmoretoDB")]
    partial class addmoretoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CAC_Management.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("CAC_Management.Models.st_routine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("day")
                        .IsRequired();

                    b.Property<string>("instructor")
                        .IsRequired();

                    b.Property<string>("sub")
                        .IsRequired();

                    b.Property<string>("time")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("student_routine");
                });

            modelBuilder.Entity("CAC_Management.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Contact");

                    b.Property<DateTime>("DOB");

                    b.Property<int>("DueAmount");

                    b.Property<int>("DueAmount2");

                    b.Property<string>("Email");

                    b.Property<string>("FatherName");

                    b.Property<string>("Gender");

                    b.Property<string>("MotherName");

                    b.Property<string>("Password");

                    b.Property<int>("PayAmount");

                    b.Property<int>("PaymentStatus");

                    b.Property<string>("StudentName");

                    b.Property<int>("TuitionFee");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("CAC_Management.Models.StudentAttendance", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("S_Name");

                    b.Property<int>("Status");

                    b.HasKey("S_Id");

                    b.ToTable("StudentAttendance");
                });

            modelBuilder.Entity("CAC_Management.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Contact");

                    b.Property<string>("Email");

                    b.Property<int>("PaidAmount");

                    b.Property<string>("Password");

                    b.Property<int>("Payment_Status");

                    b.Property<int>("Salary");

                    b.Property<string>("TeacherName");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
